version: '3.8'

services:
  ai-anchor:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - CUDA_VISIBLE_DEVICES=0
      - HOST=0.0.0.0
      - PORT=8000
    env_file:
      - .env
    volumes:
      # Model cache
      - ai-anchor-models:/root/.cache/huggingface
      - ai-anchor-ollama:/root/.ollama
      # Development code (for development only)
      # - ./src:/app/src
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Optional: Ollama service (if running separately)
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ai-anchor-ollama:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped
    command: serve

volumes:
  ai-anchor-models:
    driver: local
  ai-anchor-ollama:
    driver: local

networks:
  default:
    driver: bridge